----------------------------------
-- QUESTION 1 
--  Create a PL SQL script that uses
--  cursor to print information for 
--  customers who own a given make, 
--  model and year of a car. The 
--  three values must be entered by 
--  the user. Use SI database.
--
-- Contributor : 
----------------------------------