----------------------------------
-- QUESTION 3 - B
--  Which movie(s) is/are available 
--  right now to rent out? Display 
--  their names/titles.
--
-- Contributor : 
----------------------------------