----------------------------------
-- QUESTION 3 - D
--  Show the names of the customers 
--  and the number of movies rented 
--  by him.
--
-- Contributor : Benjamin Ahola
----------------------------------